// <auto-generated />
using System;
using Meu_Dindin.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeuDinDin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MeuDinDin.Models.Desafio", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Descricao").IsRequired().HasColumnType("TEXT");
                b.Property<int>("DuracaoDias").HasColumnType("INTEGER");
                b.Property<string>("Tipo").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Titulo").IsRequired().HasColumnType("TEXT");
                b.Property<int>("XpRecompensa").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.ToTable("Desafios");
                b.HasData(
                    new { Id = 1, Descricao = "Não peça delivery por 7 dias e economize.", DuracaoDias = 7,  Tipo = "economia", Titulo = "7 dias sem delivery",        XpRecompensa = 150 },
                    new { Id = 2, Descricao = "Registre suas transações todos os dias por 30 dias.", DuracaoDias = 30, Tipo = "registro", Titulo = "Registrar 30 dias seguidos", XpRecompensa = 300 },
                    new { Id = 3, Descricao = "Guarde pelo menos 10% da sua renda este mês.",       DuracaoDias = 30, Tipo = "meta",     Titulo = "Guardar 10% da renda",       XpRecompensa = 200 },
                    new { Id = 4, Descricao = "Evite gastos não essenciais por 7 dias.",            DuracaoDias = 7,  Tipo = "economia", Titulo = "Semana sem compras supérfluas", XpRecompensa = 100 }
                );
            });

            modelBuilder.Entity("MeuDinDin.Models.DesafioUsuario", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<bool>("Concluido").HasColumnType("INTEGER");
                b.Property<DateTime?>("ConcluidoEm").HasColumnType("TEXT");
                b.Property<int>("DesafioId").HasColumnType("INTEGER");
                b.Property<int>("DiaAtual").HasColumnType("INTEGER");
                b.Property<DateTime>("IniciadoEm").HasColumnType("TEXT");
                b.Property<int>("UsuarioId").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("DesafioId");
                b.HasIndex("UsuarioId");
                b.ToTable("DesafiosUsuarios");
            });

            modelBuilder.Entity("MeuDinDin.Models.Investimento", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("CriadoEm").HasColumnType("TEXT");
                b.Property<DateTime>("DataAporte").HasColumnType("TEXT");
                b.Property<string>("Tipo").IsRequired().HasColumnType("TEXT");
                b.Property<int>("UsuarioId").HasColumnType("INTEGER");
                b.Property<decimal>("Valor").HasColumnType("decimal(18,2)");
                b.HasKey("Id");
                b.HasIndex("UsuarioId");
                b.ToTable("Investimentos");
            });

            modelBuilder.Entity("MeuDinDin.Models.Medalha", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Descricao").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Emoji").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Titulo").IsRequired().HasColumnType("TEXT");
                b.HasKey("Id");
                b.ToTable("Medalhas");
                b.HasData(
                    new { Id = 1, Descricao = "Criou sua primeira meta financeira.",       Emoji = "🏅", Titulo = "Primeira meta"   },
                    new { Id = 2, Descricao = "Registrou transações por 7 dias seguidos.", Emoji = "🔥", Titulo = "7 dias seguidos" },
                    new { Id = 3, Descricao = "Economizou em 3 meses consecutivos.",       Emoji = "🏆", Titulo = "Economista"      },
                    new { Id = 4, Descricao = "Completou seu primeiro quiz de educação.",  Emoji = "📚", Titulo = "1º quiz feito"   },
                    new { Id = 5, Descricao = "Fez seu primeiro investimento.",            Emoji = "📈", Titulo = "Investidor"      },
                    new { Id = 6, Descricao = "Atingiu o nível 10.",                      Emoji = "🚀", Titulo = "Nível 10"        }
                );
            });

            modelBuilder.Entity("MeuDinDin.Models.MedalhaUsuario", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<DateTime>("ConquistadaEm").HasColumnType("TEXT");
                b.Property<int>("MedalhaId").HasColumnType("INTEGER");
                b.Property<int>("UsuarioId").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("MedalhaId");
                b.HasIndex("UsuarioId");
                b.ToTable("MedalhasUsuarios");
            });

            modelBuilder.Entity("MeuDinDin.Models.Meta", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Cor").IsRequired().HasColumnType("TEXT");
                b.Property<DateTime>("CriadoEm").HasColumnType("TEXT");
                b.Property<string>("Nome").IsRequired().HasColumnType("TEXT");
                b.Property<DateTime>("Prazo").HasColumnType("TEXT");
                b.Property<int>("UsuarioId").HasColumnType("INTEGER");
                b.Property<decimal>("ValorAtual").HasColumnType("decimal(18,2)");
                b.Property<decimal>("ValorTotal").HasColumnType("decimal(18,2)");
                b.HasKey("Id");
                b.HasIndex("UsuarioId");
                b.ToTable("Metas");
            });

            modelBuilder.Entity("MeuDinDin.Models.OnboardingResposta", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<int>("PerguntaIndex").HasColumnType("INTEGER");
                b.Property<int>("RespostaIndex").HasColumnType("INTEGER");
                b.Property<string>("RespostaTexto").IsRequired().HasColumnType("TEXT");
                b.Property<int>("UsuarioId").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("UsuarioId");
                b.ToTable("OnboardingRespostas");
            });

            modelBuilder.Entity("MeuDinDin.Models.Transacao", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<string>("Categoria").IsRequired().HasColumnType("TEXT");
                b.Property<DateTime>("CriadoEm").HasColumnType("TEXT");
                b.Property<DateTime>("Data").HasColumnType("TEXT");
                b.Property<string>("Descricao").IsRequired().HasColumnType("TEXT");
                b.Property<string>("FormaPagamento").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Tipo").IsRequired().HasColumnType("TEXT");
                b.Property<int>("UsuarioId").HasColumnType("INTEGER");
                b.Property<decimal>("Valor").HasColumnType("decimal(18,2)");
                b.HasKey("Id");
                b.HasIndex("UsuarioId", "Data");
                b.ToTable("Transacoes");
            });

            modelBuilder.Entity("MeuDinDin.Models.Usuario", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                b.Property<bool>("AltoContraste").HasColumnType("INTEGER");
                b.Property<DateTime>("CriadoEm").HasColumnType("TEXT");
                b.Property<string>("DesafioFinanceiro").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Email").IsRequired().HasColumnType("TEXT");
                b.Property<string>("FonteRenda").IsRequired().HasColumnType("TEXT");
                b.Property<string>("FotoUrl").HasColumnType("TEXT");
                b.Property<string>("NivelExperiencia").IsRequired().HasColumnType("TEXT");
                b.Property<string>("NomeTitulo").IsRequired().HasColumnType("TEXT");
                b.Property<string>("Nome").IsRequired().HasColumnType("TEXT");
                b.Property<string>("ObjetivoFinanceiro").IsRequired().HasColumnType("TEXT");
                b.Property<string>("PerfilInvestidor").IsRequired().HasColumnType("TEXT");
                b.Property<bool>("PreferenciaLibras").HasColumnType("INTEGER");
                b.Property<bool>("ReduzirAnimacoes").HasColumnType("INTEGER");
                b.Property<string>("SenhaHash").IsRequired().HasColumnType("TEXT");
                b.Property<bool>("TextoGrande").HasColumnType("INTEGER");
                b.Property<int>("Moedas").HasColumnType("INTEGER");
                b.Property<int>("Nivel").HasColumnType("INTEGER");
                b.Property<int>("PorcentagemPoupanca").HasColumnType("INTEGER");
                b.Property<int>("XP").HasColumnType("INTEGER");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Usuarios");
            });

            // ── Relacionamentos ───────────────────────────────────────────────
            modelBuilder.Entity("MeuDinDin.Models.DesafioUsuario", b =>
            {
                b.HasOne("MeuDinDin.Models.Desafio","Desafio").WithMany().HasForeignKey("DesafioId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("MeuDinDin.Models.Usuario","Usuario").WithMany("Desafios").HasForeignKey("UsuarioId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Desafio"); b.Navigation("Usuario");
            });

            modelBuilder.Entity("MeuDinDin.Models.Investimento", b =>
            {
                b.HasOne("MeuDinDin.Models.Usuario","Usuario").WithMany("Investimentos").HasForeignKey("UsuarioId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Usuario");
            });

            modelBuilder.Entity("MeuDinDin.Models.MedalhaUsuario", b =>
            {
                b.HasOne("MeuDinDin.Models.Medalha","Medalha").WithMany().HasForeignKey("MedalhaId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("MeuDinDin.Models.Usuario","Usuario").WithMany("Medalhas").HasForeignKey("UsuarioId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Medalha"); b.Navigation("Usuario");
            });

            modelBuilder.Entity("MeuDinDin.Models.Meta", b =>
            {
                b.HasOne("MeuDinDin.Models.Usuario","Usuario").WithMany("Metas").HasForeignKey("UsuarioId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Usuario");
            });

            modelBuilder.Entity("MeuDinDin.Models.OnboardingResposta", b =>
            {
                b.HasOne("MeuDinDin.Models.Usuario","Usuario").WithMany("OnboardingRespostas").HasForeignKey("UsuarioId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Usuario");
            });

            modelBuilder.Entity("MeuDinDin.Models.Transacao", b =>
            {
                b.HasOne("MeuDinDin.Models.Usuario","Usuario").WithMany("Transacoes").HasForeignKey("UsuarioId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Usuario");
            });

            modelBuilder.Entity("MeuDinDin.Models.Usuario", b =>
            {
                b.Navigation("Desafios");
                b.Navigation("Investimentos");
                b.Navigation("Medalhas");
                b.Navigation("Metas");
                b.Navigation("OnboardingRespostas");
                b.Navigation("Transacoes");
            });
#pragma warning restore 612, 618
        }
    }
}